import Link from 'next/link';
import {Trophy,Users,Swords,Globe} from 'lucide-react';
import {serverApi} from '@/lib/server-api';
import {type Tournament,type Community,date,human} from '@/lib/catalog';
import {TournamentCard} from '@/components/tournament-card';
import {Button} from '@/components/ui/button';
export const dynamic='force-dynamic';
export default async function Home(){const [tournaments,stats]=await Promise.all([serverApi<Tournament[]>('/tournaments?limit=12'),serverApi<Community>('/community')]);const featured=tournaments.slice(0,3);return <><section className="hero"><div className="eyebrow">THE HOME OF COMMUNITY eFOOTBALL</div><h1>Your next match.<br/><span className="lime">Your next moment.</span></h1><p>Find your competition. Take on the community.<br/>Turn every match into something worth playing for.</p><div className="actions"><Button asChild><Link href="/tournaments">Explore tournaments ↗</Link></Button><Button asChild variant="outline"><Link href="/admin">Host a tournament</Link></Button></div><span className="hero-note">PLAY IN eFOOTBALL. COMPETE ON TOUCHLINE.</span></section><section className="stats" aria-label="Community statistics">{[[Trophy,stats.tournaments,'Active tournaments'],[Users,stats.players,'Community players'],[Swords,stats.matches,'Matches played'],[Globe,stats.countries,'Countries competing']].map(([Icon,value,label])=>{const Glyph=Icon as typeof Trophy;return <div className="stat" key={String(label)}><Glyph size={21}/><strong>{String(value)}</strong><span>{String(label)}</span></div>})}</section><div className="section-head"><div><h2>Find your next challenge</h2><p className="muted">A place for every player. A tournament for every ambition.</p></div><Link href="/tournaments" className="lime small">View all tournaments ↗</Link></div><div className="grid3">{featured.length?featured.map(t=><TournamentCard key={t.id} t={t}/>):<div className="panel empty">No tournaments are available yet. Check back soon.</div>}</div><div className="lower-grid"><section><div className="section-head"><h2>Coming up on the pitch</h2><span className="muted small">Dates in UTC</span></div><div className="card">{tournaments.filter(t=>new Date(t.startsAt)>new Date()).slice(0,3).map(t=><Link key={t.id} className="match-row" href={'/tournaments/'+t.slug}><div className="date-box"><span className="small">{new Date(t.startsAt).toLocaleDateString('en',{month:'short',timeZone:'UTC'}).toUpperCase()}</span><strong>{new Date(t.startsAt).getUTCDate()}</strong></div><div className="grow"><h3 style={{fontSize:15}}>{t.name}</h3><span className="small muted">{human(t.platform)} · {t.region} · {date(t.startsAt)}</span></div><span className="badge">{human(t.status)}</span></Link>)}</div></section><section id="how-it-works"><div className="section-head"><h2>From kickoff to glory</h2></div><div className="card">{[['Find your tournament','Choose your platform, format, and challenge.'],['Join. Check in. Game on.','Meet your opponent and play in eFootball.'],['Report the result. Rise up.','Submit your score and follow your progress.']].map(([t,d],i)=><div className="how" key={t}><span className="step-circle">0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></section></div></>}

