'use client';
import Link from 'next/link';
import {Trophy,Users,Swords,Globe} from 'lucide-react';
import {api} from '@/lib/api';
import {useQuery} from '@tanstack/react-query';
import {type Tournament,type Community,date,human} from '@/lib/catalog';
import {TournamentCard} from '@/components/tournament-card';
import {Button} from '@/components/ui/button';
export function HomeFeed(){
const retry=(count:number,error:Error)=>count<4&&(!('status' in error)||[0,408,502,503,504].includes(Number(error.status)));
const competitions=useQuery({queryKey:['home-tournaments'],queryFn:()=>api<Tournament[]>('/tournaments?limit=12',{anonymous:true}),retry,retryDelay:attempt=>Math.min(2000*2**attempt,10000)});
const community=useQuery({queryKey:['home-community'],queryFn:()=>api<Community>('/community',{anonymous:true}),retry,retryDelay:attempt=>Math.min(2000*2**attempt,10000)});
const tournaments=competitions.data||[];
const stats=community.data||{tournaments:'—',players:'—',matches:'—',countries:'—'};
const featured=tournaments.slice(0,3);return <><section className="stats" aria-label="Community statistics">{[[Trophy,stats.tournaments,'Active tournaments'],[Users,stats.players,'Community players'],[Swords,stats.matches,'Matches played'],[Globe,stats.countries,'Countries competing']].map(([Icon,value,label])=>{const Glyph=Icon as typeof Trophy;return <div className="stat" key={String(label)}><Glyph size={21}/><strong>{String(value)}</strong><span>{String(label)}</span></div>})}</section><div className="section-head"><div><h2>Find your next challenge</h2><p className="muted">A place for every player. A tournament for every ambition.</p></div><Link href="/tournaments" className="lime small">View all tournaments ↗</Link></div>{!competitions.data&&<section className="panel" role="status" aria-live="polite">{competitions.isFetching?<><h2>Connecting to the tournament service…</h2><p className="muted">This can take a little longer on your first visit. Your tournaments will appear here automatically.</p><div className="skeleton"/></>:competitions.isError?<><h2>Tournaments are temporarily unavailable</h2><p className="muted">Please check your connection and try again. You can still explore the site.</p><Button onClick={()=>{void competitions.refetch();void community.refetch()}}>Try again</Button></>:null}</section>}
{community.isError&&!community.isFetching&&<p className="small muted">Community statistics are temporarily unavailable. <button className="button button-ghost" onClick={()=>void community.refetch()}>Retry statistics</button></p>}
<div className="grid3">{featured.length?featured.map(t=><TournamentCard key={t.id} t={t}/>):competitions.isSuccess?<div className="panel empty">No tournaments are available yet. Check back soon.</div>:null}</div><div className="lower-grid"><section><div className="section-head"><h2>Coming up on the pitch</h2><span className="muted small">Dates in UTC</span></div><div className="card">{tournaments.filter(t=>new Date(t.startsAt)>new Date()).slice(0,3).map(t=><Link key={t.id} className="match-row" href={'/tournaments/'+t.slug}><div className="date-box"><span className="small">{new Date(t.startsAt).toLocaleDateString('en',{month:'short',timeZone:'UTC'}).toUpperCase()}</span><strong>{new Date(t.startsAt).getUTCDate()}</strong></div><div className="grow"><h3 style={{fontSize:15}}>{t.name}</h3><span className="small muted">{human(t.platform)} · {t.region} · {date(t.startsAt)}</span></div><span className="badge">{human(t.status)}</span></Link>)}</div></section><section id="how-it-works"><div className="section-head"><h2>From kickoff to glory</h2></div><div className="card">{[['Find your tournament','Choose your platform, format, and challenge.'],['Join. Check in. Game on.','Meet your opponent and play in eFootball.'],['Report the result. Rise up.','Submit your score and follow your progress.']].map(([t,d],i)=><div className="how" key={t}><span className="step-circle">0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></section></div></>}

