'use client';
import {useState} from 'react';
import {useForm,type FieldValues,type Path,type DefaultValues} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import type {z} from 'zod';
import {useQueryClient} from '@tanstack/react-query';
import {useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {registerSchema,loginSchema,emailSchema,resetPasswordSchema,tokenSchema} from '@touchline/shared';
import {authDestination} from '@/lib/auth-destination';
import {api,ApiError} from '@/lib/api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {PasswordInput} from '@/components/ui/password-input';
import {Feedback} from '@/components/ui/feedback';
type Kind='register'|'login'|'forgot-password'|'reset-password'|'verify-email';
interface Field{key:string;label:string;type?:string;autocomplete?:string;placeholder?:string;options?:Array<[string,string]>}
function Form<T extends FieldValues>({schema,defaults,fields,label,onSubmit}:{schema:z.ZodType<T,T>;defaults:DefaultValues<T>;fields:Field[];label:string;onSubmit:(data:T)=>Promise<string|void>}){
 const [message,setMessage]=useState(''),[failure,setFailure]=useState('');
 const {register,handleSubmit,setError,formState:{errors,isSubmitting,isSubmitSuccessful}}=useForm<T>({resolver:zodResolver(schema),defaultValues:defaults});
 return <form noValidate onSubmit={handleSubmit(async data=>{setFailure('');setMessage('');try{setMessage(await onSubmit(data)||'')}catch(error){if(error instanceof ApiError){for(const item of error.errors)setError(item.path as Path<T>,{message:item.message});setFailure(error.message)}else setFailure('Something went wrong. Please try again.')}})}><div className="form-fields">{fields.map(f=><div className="field" key={f.key}><label htmlFor={f.key}>{f.label}</label>{f.options?<select id={f.key} {...register(f.key as Path<T>)} aria-invalid={!!errors[f.key]} aria-describedby={errors[f.key]?`${f.key}-error`:undefined}>{f.options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>:f.type==='password'?<PasswordInput id={f.key} label={f.label} autoComplete={f.autocomplete} showStrength={f.key==='password'&&f.autocomplete==='new-password'} {...register(f.key as Path<T>)} aria-invalid={!!errors[f.key]} aria-describedby={errors[f.key]?`${f.key}-error`:undefined}/>:<Input id={f.key} type={f.type||'text'} autoComplete={f.autocomplete} placeholder={f.placeholder} {...register(f.key as Path<T>)} aria-invalid={!!errors[f.key]} aria-describedby={errors[f.key]?`${f.key}-error`:undefined}/>}<p className="field-error" id={`${f.key}-error`}>{typeof errors[f.key]?.message==='string'?String(errors[f.key]?.message):''}</p></div>)}</div><Feedback message={failure} error/><Feedback message={message}/><Button type="submit" className="full" disabled={isSubmitting||(isSubmitSuccessful&&!!message)}>{isSubmitting?'Please wait…':label}</Button></form>
}
const email:Field={key:'email',label:'Email address',type:'email',autocomplete:'email',placeholder:'you@example.com'};
const password:Field={key:'password',label:'Password',type:'password',autocomplete:'current-password'};
const confirm:Field={key:'confirmPassword',label:'Confirm password',type:'password',autocomplete:'new-password'};
export function AuthForm({kind}:{kind:Kind}){const router=useRouter(),cache=useQueryClient(),params=useSearchParams();const token=params.get('token')||'';
 if(kind==='register')return <><Form schema={registerSchema} defaults={{name:'',username:'',email:'',password:'',confirmPassword:'',country:'BD',efootballUsername:'',platform:'STEAM_PC'}} fields={[{key:'name',label:'Full name',autocomplete:'name'},{key:'username',label:'Touchline username',autocomplete:'username'},email,{...password,autocomplete:'new-password'},confirm,{key:'country',label:'Country',options:[['BD','Bangladesh'],['GB','United Kingdom'],['US','United States'],['JP','Japan'],['PT','Portugal'],['DE','Germany'],['IN','India'],['ES','Spain'],['BR','Brazil']]},{key:'efootballUsername',label:'eFootball username'},{key:'platform',label:'Platform',options:[['STEAM_PC','PC'],['MOBILE','Mobile']]}]} label="Create account →" onSubmit={async data=>{await api('/auth/register',{method:'POST',body:data,anonymous:true});await api('/auth/login',{method:'POST',body:{email:data.email,password:data.password},anonymous:true});await cache.invalidateQueries({queryKey:['session']});router.replace(authDestination(params.get('next')));router.refresh();}}/><p className="small muted" style={{marginTop:18}}>Your name, username, country, platform and game username are public. Email, password and account settings stay private.</p><Link className="lime small" href="/verify-email">Resend verification email</Link></>;
 if(kind==='login')return <Form schema={loginSchema} defaults={{email:'',password:''}} fields={[{...email,label:'Email, username or eFootball username',type:'text',autocomplete:'username',placeholder:'Your email or player name'},password]} label="Log in →" onSubmit={async data=>{await api('/auth/login',{method:'POST',body:data,anonymous:true});await cache.invalidateQueries({queryKey:['session']});router.replace(authDestination(params.get('next')));router.refresh()}}/>;
 if(kind==='forgot-password')return <Form schema={emailSchema} defaults={{email:''}} fields={[email]} label="Send reset link" onSubmit={async data=>{const result=await api<{deliveryMode:string}>('/auth/forgot-password',{method:'POST',body:data,anonymous:true});return result.deliveryMode==='development'?'Local preview: if that account exists, its reset email is saved in the private .local/mail folder on this computer. No email is sent to your inbox.':'If that account exists, a reset link has been requested. Check your inbox.'}}/>;
 if(kind==='reset-password')return token?<Form schema={resetPasswordSchema} defaults={{token,password:'',confirmPassword:''}} fields={[{...password,autocomplete:'new-password',label:'New password'},confirm]} label="Reset password" onSubmit={async data=>{await api('/auth/reset-password',{method:'POST',body:data,anonymous:true});return 'Your password has changed and previous sessions are closed. Log in with your new password.'}}/>:<Feedback message="This reset link is incomplete. Request a new password reset email." error/>;
 return token?<><Form schema={tokenSchema} defaults={{token}} fields={[]} label="Verify my email" onSubmit={async data=>{await api('/auth/verify-email',{method:'POST',body:data,anonymous:true});await cache.invalidateQueries({queryKey:['session']});return 'Your email is verified. You can now log in.'}}/><p className="small" style={{marginTop:18}}><Link className="lime" href="/verify-email">Expired or already-used link? Request a new verification email</Link></p></>:<Form schema={emailSchema} defaults={{email:''}} fields={[email]} label="Resend verification" onSubmit={async data=>{const result=await api<{deliveryMode:string}>('/auth/resend-verification',{method:'POST',body:data,anonymous:true});return result.deliveryMode==='development'?'Local preview: if the account needs verification, its new email is saved in the private .local/mail folder on this computer. Open the newest message for your address; previous links expire when you resend. No email is sent to your inbox.':'If the account needs verification, a new link has been requested. Use the newest email; previous links expire when you resend.'}}/>
}
