import {DEFAULT_COVER_IMAGE} from '@/lib/cover-image';
import Link from 'next/link';
import {Trophy,Target,ShieldCheck} from 'lucide-react';
import {human} from '@/lib/catalog';
import {ProfilePhoto} from './profile-photo';
export interface PublicPlayer {
 id:string;name:string;username:string;createdAt:string;
 profile:{platform:string;country:string;efootballUsername:string;avatarUrl:string|null}|null;
 stats:{played:number;wins:number;draws:number;losses:number;goalsFor:number;goalsAgainst:number;goalDifference:number};
 history:Array<{tournament:{name:string;slug:string;status:string;startsAt:string;format?:string}}>|null;
 achievements:Array<{achievement:{name:string;description:string}}>;
}
export function ProfileOverview({user,editable=false}:{user:PublicPlayer;editable?:boolean}) {
 const winRate=user.stats.played?Math.round(user.stats.wins/user.stats.played*1000)/10:0;
 const active=user.history?.filter(h=>!['COMPLETED','CANCELLED'].includes(h.tournament.status)).length||0;
 return <div className="profile-page"><section className="profile-cover" style={{backgroundImage:`linear-gradient(180deg,#0d141b70 0%,#0d141bc9 55%,#0d141bf5 100%),url("${DEFAULT_COVER_IMAGE}")`,backgroundSize:"cover",backgroundPosition:"center"}}><div className="profile-cover-top"><div><div className="brand lime">TOUCHLINE.</div><div className="eyebrow">eFootball player profile</div></div><span className="badge"><ShieldCheck size={13}/> Community competitor</span></div><div className="profile-cover-bottom"><ProfilePhoto name={user.name} url={user.profile?.avatarUrl} editable={editable}/><div className="profile-identity"><p className="small muted">Member since {new Date(user.createdAt).toLocaleDateString()}</p><h1>{user.name}<span className="lime"> ·</span></h1><p className="muted">@{user.username}</p><div className="meta"><span>eFootball: <b className="lime">{user.profile?.efootballUsername||'Not provided'}</b></span><span>{human(user.profile?.platform||'Not set')}</span><span>{user.profile?.country}</span></div></div><div className="profile-summary">{[['Win rate',winRate+'%'],['Matches',user.stats.played],['Tourneys',user.history?.length??'Private']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section>
 <div className="profile-columns"><section className="panel profile-performance"><div className="row"><h2><i/>Tournament stats</h2><span className="badge">Official records</span></div><p className="small muted">Based on confirmed results in public Touchline tournaments.</p><div className="record-grid">{[['Played',user.stats.played,'Total games'],['Wins',user.stats.wins,'Victories'],['Draws',user.stats.draws,'Tied games'],['Losses',user.stats.losses,'Defeats']].map(([label,value,hint])=><div key={label} className={label==='Wins'?'win-record':''}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>)}</div><h3 className="metric-heading">Goal scoring metrics</h3><div className="goal-grid">{[['Goals for',user.stats.goalsFor],['Goals against',user.stats.goalsAgainst],['Goal difference',user.stats.goalDifference]].map(([label,value])=><div key={label}><Target size={20}/><div><span>{label}</span><strong>{value}</strong></div></div>)}</div><div className="feedback"><ShieldCheck size={20}/><span>{user.stats.played?'Every goal counts. These records update when tournament match results become official.':'Ready for your first result? Complete a tournament match to start building your official record.'}</span></div></section>
 <aside><section className="panel profile-history"><div className="row"><h2><i/>Tournament history</h2>{user.history&&<span className="badge">{active} active</span>}</div>{user.history===null?<div className="empty">This player keeps their tournament history private.</div>:user.history.length?user.history.map(({tournament:t})=><Link className="profile-history-card" key={t.slug} href={'/tournaments/'+t.slug+'?tab='+(t.format==='LEAGUE'?'Standings':'Bracket')}><div className="row"><Trophy size={28}/><strong>{t.name}</strong><span className="badge">{human(t.status)}</span></div><div className="row small muted"><span>{new Date(t.startsAt).toLocaleDateString()} · {human(t.format||'Tournament')}</span><span className="lime">{t.format==='LEAGUE'?'View table':'View tournament'} →</span></div></Link>):<div className="empty">No tournaments yet. Your next competition starts here.</div>}<div className="profile-player-id small muted">Touchline player · @{user.username}</div></section><section className="panel profile-achievements"><h2>Achievements</h2>{user.achievements.length?user.achievements.map(a=><p key={a.achievement.name}><Trophy size={16}/> <strong>{a.achievement.name}</strong><br/><span className="small muted">{a.achievement.description}</span></p>):<p className="small muted">Play official tournament matches to earn achievements.</p>}</section></aside></div></div>;
}

