'use client';
import {IdentityNotice} from './identity-notice';
import {useState} from 'react';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {useQueryClient} from '@tanstack/react-query';
import {useRouter} from 'next/navigation';
import {profileSchema,type ProfileInput,type SessionUser} from '@touchline/shared';
import {api,ApiError} from '@/lib/api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Feedback} from '@/components/ui/feedback';
export function ProfileForm({user}:{user:SessionUser}){const router=useRouter(),cache=useQueryClient(),[message,setMessage]=useState(''),[failure,setFailure]=useState('');const {register,handleSubmit,setError,formState:{errors,isSubmitting}}=useForm<ProfileInput>({resolver:zodResolver(profileSchema),defaultValues:{name:user.name,country:user.profile?.country||'BD',platform:user.profile?.platform==='MOBILE'?'MOBILE':user.profile?.platform==='STEAM_PC'?'STEAM_PC':undefined,efootballUsername:user.profile?.efootballUsername||'',efootballUserId:user.profile?.efootballUserId||'',platformUsername:user.profile?.platformUsername||'',timezone:user.profile?.timezone||'UTC',publicHistory:user.profile?.publicHistory??true}});return <form className="panel" onSubmit={handleSubmit(async body=>{setMessage('');setFailure('');try{await api('/users/me',{method:'PATCH',body});setMessage('Profile updated.');await cache.invalidateQueries({queryKey:['session']});await cache.invalidateQueries({queryKey:['identity-status']});router.refresh()}catch(e){setFailure(e instanceof Error?e.message:'Update failed.');if(e instanceof ApiError)for(const item of e.errors)setError(item.path as keyof ProfileInput,{message:item.message})}})}><h2>Public player information</h2><IdentityNotice/><div className="form-fields">{[['name','Full name'],['country','Country code (two letters)'],['efootballUsername','eFootball username'],['efootballUserId','eFootball User ID'],['platformUsername','Platform username']].map(([key,label])=><div className="field" key={key}><label htmlFor={key}>{label}</label><Input id={key} {...register(key as keyof ProfileInput)} aria-invalid={!!errors[key as keyof ProfileInput]}/><p className="field-error">{errors[key as keyof ProfileInput]?.message}</p></div>)}<div className="field"><label htmlFor="platform">Platform</label><select id="platform" {...register('platform')}><option value="" disabled>Choose PC or Mobile</option><option value="STEAM_PC">PC</option><option value="MOBILE">Mobile</option></select><p className="field-error">{errors.platform?.message}</p>{user.profile&& !['STEAM_PC','MOBILE'].includes(user.profile.platform)&&<p className="small muted">Your existing platform is preserved. Choose PC or Mobile if you want to update it.</p>}</div><h2>Private preferences</h2><div className="field"><label htmlFor="timezone">Timezone</label><select id="timezone" {...register('timezone')}>{Array.from(new Set([user.profile?.timezone||'UTC','UTC','Asia/Dhaka','Asia/Tokyo','Europe/London','America/New_York'])).map(t=><option key={t}>{t}</option>)}</select><p className="field-error">{errors.timezone?.message}</p></div><label className="small"><input type="checkbox" {...register('publicHistory')}/> Show tournament history on my public profile</label></div><Feedback message={message}/><Feedback message={failure} error/><Button type="submit" disabled={isSubmitting}>{isSubmitting?'Saving…':'Save profile'}</Button></form>}

