'use client';
import Link from 'next/link';
import {useQuery} from '@tanstack/react-query';
import {api} from '@/lib/api';
import type {PlayerDashboard} from '@/lib/competition';
import {MatchList} from '@/features/tournaments/competition-view';
import {QueryState} from '@/components/query-state';
import {Button} from '@/components/ui/button';
export function PlayerArena({section='dashboard'}:{section?:string}){const {data,error,isPending,refetch}=useQuery({queryKey:['dashboard'],queryFn:()=>api<PlayerDashboard>('/dashboard')});return <><h1>{section==='dashboard'?'Your arena':section==='notifications'?'Notifications':section==='matches'?'My matches':'My tournaments'}</h1><p className="muted">Your competition, all in one place.</p><QueryState pending={isPending} error={error} retry={()=>void refetch()}/>{data&&<>{section==='dashboard'&&<div className="stats">{Object.entries(data.statistics).map(([key,n])=><div className="stat" key={key}><strong>{n}{key==='winRate'?'%':''}</strong><span>{key}</span></div>)}</div>}{(section==='dashboard'||section==='matches')&&<section><div className="section-head"><h2>{section==='dashboard'?'Upcoming matches':'Match history'}</h2></div><MatchList matches={section==='matches'?data.matches:data.matches.filter(m=>!['COMPLETED','CANCELLED','WALKOVER'].includes(m.status))}/></section>}{(section==='dashboard'||section==='tournaments')&&<section><div className="section-head"><h2>Your tournaments</h2><Link className="lime small" href="/tournaments">Explore tournaments ↗</Link></div><div className="card">{data.registrations.length?data.registrations.map(r=><Link href={'/tournaments/'+r.tournament.slug} className="match-row" key={r.id}><div className="grow"><h3>{r.tournament.name}</h3></div><span className="badge">{r.status}</span></Link>):<div className="empty">You haven’t joined a tournament yet.</div>}</div></section>}{section==='notifications'&&<div className="panel"><Button variant="outline" onClick={async()=>{await api('/notifications/read-all',{method:'PATCH'});await refetch()}}>Mark all as read</Button>{data.notifications.length?data.notifications.map(n=><div className="match-row" key={n.id}><div className="grow"><Link href={n.link||'/dashboard'}><h3>{n.title}</h3></Link><p className="muted small">{n.message}</p><span className="small muted">{new Date(n.createdAt).toLocaleString()}</span></div>{!n.readAt&&<Button variant="ghost" onClick={async()=>{await api('/notifications/'+n.id+'/read',{method:'PATCH'});await refetch()}}>Mark read</Button>}</div>):<div className="empty">No notifications yet.</div>}</div>}</>}</>}
