import {rankScope} from './ranking.service.js';
import {randomUUID} from 'node:crypto';
import type {Prisma,Tournament,TournamentParticipant} from '../generated/prisma/client.js';
import {AppError} from '../utils/errors.js';
import {transaction} from './transaction.js';
import {roundRobin,distributeGroups} from './competition-engine.js';
import {audit} from './tournament.service.js';
export async function createKnockout(tx:Prisma.TransactionClient,t:Tournament,players:TournamentParticipant[]){if(players.length<2)throw new AppError(409,'At least two players are required.');const size=2**Math.ceil(Math.log2(players.length)),rounds=Math.log2(size);let seeds=[1,2];while(seeds.length<size)seeds=seeds.flatMap(x=>[x,seeds.length*2+1-x]);const ids=Array.from({length:rounds},(_,r)=>Array.from({length:size/2**(r+1)},()=>randomUUID()));const thirdId=t.thirdPlaceEnabled&&size>=4?randomUUID():null;if(thirdId)await tx.match.create({data:{id:thirdId,tournamentId:t.id,stage:'THIRD_PLACE',round:rounds,position:1}});
 for(let r=rounds-1;r>=0;r--){for(let p=0;p<ids[r]!.length;p++){const home=r===0?players[seeds[p*2]!-1]:undefined,away=r===0?players[seeds[p*2+1]!-1]:undefined;await tx.match.create({data:{id:ids[r]![p]!,tournamentId:t.id,stage:r===rounds-1?'FINAL':'KNOCKOUT',round:r+1,position:p+1,homeId:home?.id,awayId:away?.id,nextMatchId:ids[r+1]?.[Math.floor(p/2)],nextSlot:r<rounds-1?p%2:null,loserMatchId:r===rounds-2?thirdId:null,loserSlot:r===rounds-2&&thirdId?p%2:null,scheduledAt:new Date(t.startsAt.getTime()+r*86400000)}})}}
 // A bye advances the sole entrant without fabricating a played match or goals.
 for(let p=0;p<size/2;p++){const home=players[seeds[p*2]!-1],away=players[seeds[p*2+1]!-1];if(!home||!away){const advancing=home||away;if(!advancing)throw new AppError(409,'Invalid bracket seeding.');await tx.match.update({where:{id:ids[0]![p]!},data:{status:'COMPLETED',winnerId:advancing.id,completedAt:new Date(),adminNotes:'First-round bye'}});const next=ids[1]?.[Math.floor(p/2)];if(next)await tx.match.update({where:{id:next},data:p%2?{awayId:advancing.id}:{homeId:advancing.id}})}}
}
export async function generate(actorId:string,id:string){return transaction(tx=>generateInTransaction(tx,actorId,id))}
export async function generateInTransaction(tx:Prisma.TransactionClient,actorId:string,id:string){const t=await tx.tournament.findUnique({where:{id},include:{participants:{orderBy:[{seed:'asc'},{createdAt:'asc'}]},_count:{select:{matches:true}}}});if(!t)throw new AppError(404,'Tournament not found.');if(!['REGISTRATION_CLOSED','UPCOMING'].includes(t.status))throw new AppError(409,'Close registration before generating fixtures.');if(t._count.matches)throw new AppError(409,'Fixtures already exist. They will not be overwritten.');if(t.participants.length<t.minPlayers)throw new AppError(409,'Not enough approved players.');if(t.format==='KNOCKOUT')await createKnockout(tx,t,t.participants);else{const groups=t.format==='LEAGUE'?[t.participants]:distributeGroups(t.participants,t.numberOfGroups);for(const [i,players] of groups.entries()){const group=t.format==='LEAGUE'?null:await tx.tournamentGroup.create({data:{tournamentId:id,name:'Group '+String.fromCharCode(65+i),position:i+1,members:{create:players.map(p=>({participantId:p.id}))}}});const fixtures=roundRobin(players.length,t.homeAwayLegs);await tx.match.createMany({data:fixtures.map(f=>({tournamentId:id,stage:group?'GROUP':'LEAGUE',round:f.round,position:i*100+f.position,leg:f.leg,groupId:group?.id,homeId:players[f.home]!.id,awayId:players[f.away]!.id,scheduledAt:new Date(t.startsAt.getTime()+(f.round-1)*86400000)}))});for(const p of players)await tx.standing.create({data:{tournamentId:id,participantId:p.id,groupId:group?.id,scope:group?.id||'overall'}})}}await tx.tournament.update({where:{id},data:{status:'UPCOMING',currentStage:t.format==='KNOCKOUT'?'KNOCKOUT':t.format==='LEAGUE'?'LEAGUE':'GROUP',version:{increment:1}}});await audit(tx,actorId,'FIXTURES_GENERATED',id);await tx.notification.createMany({data:t.participants.map(p=>({userId:p.userId,title:'Fixtures published',message:t.name,type:'FIXTURE',link:'/tournaments/'+t.slug}))});return {count:await tx.match.count({where:{tournamentId:id}})}}
export async function qualify(tx:Prisma.TransactionClient,t:Tournament){
 const remaining=await tx.match.count({where:{tournamentId:t.id,stage:'GROUP',status:{notIn:['COMPLETED','WALKOVER']}}});if(remaining)throw new AppError(409,'All group matches must have official results before qualification.');
 if(await tx.match.count({where:{tournamentId:t.id,stage:{in:['KNOCKOUT','FINAL']}}}))throw new AppError(409,'Knockout stage already exists.');
 const groups=await tx.tournamentGroup.findMany({where:{tournamentId:t.id},orderBy:{position:'asc'}});if(!groups.length)throw new AppError(409,'No groups exist.');
 const qualified:TournamentParticipant[]=[];for(const group of groups){const ranking=await rankScope(tx,t,group.id);if(ranking.tiedAt(t.advancingPerGroup))return {qualified:0,requiresReview:true};const top=ranking.rows.slice(0,t.advancingPerGroup);if(top.length<t.advancingPerGroup)throw new AppError(409,'A group has insufficient qualifiers.');for(const row of top)qualified.push(ranking.members.find(m=>m.id===row.participantId)!)}
 for(const p of qualified)await tx.tournamentParticipant.update({where:{id:p.id},data:{qualified:true}});await tx.tournamentGroup.updateMany({where:{tournamentId:t.id},data:{qualificationConfirmedAt:new Date()}});await createKnockout(tx,t,qualified);await tx.tournament.update({where:{id:t.id},data:{currentStage:'KNOCKOUT'}});await tx.notification.createMany({data:qualified.map(p=>({userId:p.userId,title:'You qualified for the knockout stage',message:t.name,type:'QUALIFICATION',link:'/tournaments/'+t.slug}))});return {qualified:qualified.length,requiresReview:false};
}
export async function confirmQualification(actorId:string,id:string){return transaction(async tx=>{const t=await tx.tournament.findUnique({where:{id}});if(!t||t.format!=='GROUP_KNOCKOUT'||t.status!=='ONGOING')throw new AppError(409,'This event is not ready for knockout qualification.');const result=await qualify(tx,t);if(result.requiresReview)throw new AppError(409,'A qualification place is tied. Record a manual tie-break ranking first.');await audit(tx,actorId,'QUALIFICATION_CONFIRMED',id);return result})}
