import type {Prisma,Tournament} from '../generated/prisma/client.js';
import {calculateStandings,type TableRow,type OfficialScore} from './competition-engine.js';
export async function rankScope(tx:Prisma.TransactionClient,t:Tournament,groupId:string|null=null){const members=await tx.tournamentParticipant.findMany({where:{tournamentId:t.id,...(groupId?{memberships:{some:{groupId}}}:{})}});const matches=await tx.match.findMany({where:{tournamentId:t.id,groupId,stage:groupId?'GROUP':'LEAGUE',status:{in:['COMPLETED','WALKOVER']}}});const scores:OfficialScore[]=matches.filter(m=>m.homeId&&m.awayId&&m.homeScore!==null&&m.awayScore!==null).map(m=>({homeId:m.homeId!,awayId:m.awayId!,homeScore:m.homeScore!,awayScore:m.awayScore!}));const base=calculateStandings(members.map(m=>m.id),scores,{win:t.pointsWin,draw:t.pointsDraw,loss:t.pointsLoss},t.goalDifferenceTiebreak,false);const manual=await tx.standing.findMany({where:{tournamentId:t.id,scope:groupId||'overall'}});const primary=(a:TableRow,b:TableRow)=>b.points-a.points||(t.goalDifferenceTiebreak?b.goalDifference-a.goalDifference:0)||b.goalsFor-a.goalsFor;
 const headPoints=new Map<string,number>();for(const row of base){const tied=new Set(base.filter(other=>primary(row,other)===0).map(x=>x.participantId));let points=0;for(const s of scores){if(!tied.has(s.homeId)||!tied.has(s.awayId)||![s.homeId,s.awayId].includes(row.participantId))continue;points+=s.homeScore===s.awayScore?t.pointsDraw:(s.homeScore>s.awayScore?s.homeId:s.awayId)===row.participantId?t.pointsWin:t.pointsLoss}headPoints.set(row.participantId,points)}
 const compare=(a:TableRow,b:TableRow)=>primary(a,b)||(t.headToHeadTiebreak?(headPoints.get(b.participantId)||0)-(headPoints.get(a.participantId)||0):0);
 const rank=(id:string)=>manual.find(m=>m.participantId===id)?.manualRank;
 base.sort((a,b)=>compare(a,b)||((rank(a.participantId)??999)-(rank(b.participantId)??999))||a.participantId.localeCompare(b.participantId));
 return {rows:base,members,tiedAt:(position:number)=>{const a=base[position-1],b=base[position];return !!a&&!!b&&compare(a,b)===0&&(rank(a.participantId)==null||rank(b.participantId)==null||rank(a.participantId)===rank(b.participantId))}};
}
