import {rankScope} from './ranking.service.js';
import {prisma} from '../config/prisma.js';
import {AppError} from '../utils/errors.js';
export const playerSelect={id:true,name:true,username:true,profile:{select:{avatarUrl:true,platform:true,efootballUsername:true,country:true}}} as const;
export const matchInclude={home:{include:{user:{select:playerSelect}}},away:{include:{user:{select:playerSelect}}},winner:{include:{user:{select:playerSelect}}}} as const;
export async function tournamentData(id:string){const t=await prisma.tournament.findFirst({where:{id,visibility:'PUBLIC',publishedAt:{not:null},status:{not:'DRAFT'}}});if(!t)throw new AppError(404,'Tournament not found.');const [participants,matches,standings,groups,announcements,winners]=await Promise.all([t.participantListPublic?prisma.tournamentParticipant.findMany({where:{tournamentId:id},include:{user:{select:playerSelect}},orderBy:{seed:'asc'}}):[],prisma.match.findMany({where:{tournamentId:id},include:matchInclude,orderBy:[{round:'asc'},{position:'asc'}],take:1000}),prisma.standing.findMany({where:{tournamentId:id},include:{participant:{include:{user:{select:playerSelect}}}},orderBy:[{points:'desc'},{goalDifference:'desc'},{goalsFor:'desc'}]}),prisma.tournamentGroup.findMany({where:{tournamentId:id},include:{members:{include:{participant:{include:{user:{select:playerSelect}}}}}},orderBy:{position:'asc'}}),prisma.announcement.findMany({where:{tournamentId:id,publishedAt:{not:null}},orderBy:{publishedAt:'desc'},take:50}),prisma.tournamentWinner.findMany({where:{tournamentId:id},include:{participant:{include:{user:{select:playerSelect}}}}})]);const safeMatches=matches.map(({adminNotes:_notes,...m})=>m);const ordered=[];for(const scope of groups.length?groups.map(g=>g.id):[null]){const ranked=await rankScope(prisma,t,scope);for(const r of ranked.rows){const stored=standings.find(x=>x.participantId===r.participantId&&x.groupId===scope);if(stored)ordered.push(stored)}}return {participantListPublic:t.participantListPublic,participants,matches:safeMatches,standings:ordered,groups:t.participantListPublic?groups:groups.map(g=>({...g,members:[]})),announcements,winners,statistics:statistics(matches)}}
export function statistics(matches:Array<{homeScore:number|null;awayScore:number|null;status:string}>){const completed=matches.filter(m=>['COMPLETED','WALKOVER'].includes(m.status)&&m.homeScore!==null&&m.awayScore!==null);const totalGoals=completed.reduce((n,m)=>n+m.homeScore!+m.awayScore!,0);return {totalMatches:matches.length,completedMatches:completed.length,totalGoals,averageGoals:completed.length?Number((totalGoals/completed.length).toFixed(2)):0}}
export async function dashboard(userId:string){const [registrations,matches,notifications]=await Promise.all([prisma.tournamentRegistration.findMany({where:{userId},include:{tournament:{select:{id:true,name:true,slug:true,status:true,startsAt:true}}},orderBy:{createdAt:'desc'},take:100}),prisma.match.findMany({where:{OR:[{home:{userId}},{away:{userId}}]},include:{...matchInclude,tournament:{select:{id:true,name:true,slug:true}}},orderBy:{scheduledAt:'asc'},take:200}),prisma.notification.findMany({where:{userId},orderBy:{createdAt:'desc'},take:50})]);const official=matches.filter(m=>['COMPLETED','WALKOVER'].includes(m.status)&&m.homeScore!==null&&m.awayScore!==null);const wins=official.filter(m=>m.winnerId&&(m.home?.userId===userId?m.winnerId===m.homeId:m.winnerId===m.awayId)).length;const goals=official.reduce((n,m)=>n+(m.home?.userId===userId?m.homeScore!:m.awayScore!),0);return {registrations,matches,notifications,statistics:{played:official.length,wins,goals,winRate:official.length?Math.round(wins/official.length*100):0}}}
export async function adminDashboard(){const [users,tournaments,matches,registrations,auditLogs,announcements]=await Promise.all([prisma.user.findMany({where:{deletedAt:null},take:100,orderBy:{createdAt:'desc'},select:{...playerSelect,email:true,role:true,status:true,createdAt:true}}),prisma.tournament.findMany({take:100,orderBy:{createdAt:'desc'},include:{_count:{select:{participants:true,matches:true}}}}),prisma.match.findMany({take:100,orderBy:{updatedAt:'desc'},include:{...matchInclude,tournament:{select:{name:true,slug:true}},submissions:true}}),prisma.tournamentRegistration.findMany({where:{status:'PENDING'},include:{user:{select:playerSelect},tournament:{select:{name:true}}},take:100}),prisma.auditLog.findMany({orderBy:{createdAt:'desc'},include:{actor:{select:{name:true}}},take:100}),prisma.announcement.findMany({orderBy:{createdAt:'desc'},take:100})]);return {users,tournaments,matches,registrations,auditLogs,announcements,statistics:{users:await prisma.user.count({where:{deletedAt:null}}),activeTournaments:await prisma.tournament.count({where:{status:{in:['REGISTRATION_OPEN','UPCOMING','ONGOING']}}}),completedTournaments:await prisma.tournament.count({where:{status:'COMPLETED'}}),...statistics(matches)}}}

