import type {TournamentInput} from '@touchline/shared';
import {prisma} from '../config/prisma.js';
import type {Prisma,TournamentStatus} from '../generated/prisma/client.js';
import {AppError} from '../utils/errors.js';
import {transaction} from './transaction.js';
export async function audit(tx:Prisma.TransactionClient,actorId:string,action:string,entityId:string,metadata:Prisma.InputJsonValue={}){await tx.auditLog.create({data:{actorId,action,entityType:'Tournament',entityId,metadata}})}
export async function create(actorId:string,input:TournamentInput){return transaction(async tx=>{const t=await tx.tournament.create({data:{...input,createdById:actorId}});await audit(tx,actorId,'TOURNAMENT_CREATED',t.id);return t})}
export async function update(actorId:string,id:string,input:TournamentInput){return transaction(async tx=>{const t=await tx.tournament.findUnique({where:{id},include:{_count:{select:{matches:true,participants:true}}}});if(!t)throw new AppError(404,'Tournament not found.');if(t._count.matches)throw new AppError(409,'Competition has fixtures. Edit schedules or results separately.');if(t._count.participants>input.maxPlayers)throw new AppError(409,'Capacity cannot be smaller than the registered field.');if(t._count.participants&&(input.platform!==t.platform||input.format!==t.format))throw new AppError(409,'Platform and format are locked after players join.');const result=await tx.tournament.update({where:{id},data:{...input,version:{increment:1}}});await audit(tx,actorId,'TOURNAMENT_UPDATED',id);return result})}
const transitions:Record<TournamentStatus,TournamentStatus[]>={DRAFT:['REGISTRATION_OPEN','CANCELLED'],REGISTRATION_OPEN:['REGISTRATION_CLOSED','CANCELLED'],REGISTRATION_CLOSED:['REGISTRATION_OPEN','UPCOMING','CANCELLED'],UPCOMING:['ONGOING','CANCELLED'],ONGOING:['CANCELLED'],COMPLETED:[],CANCELLED:[]};
export async function changeStatus(actorId:string,id:string,status:TournamentStatus,reason:string){return transaction(async tx=>{const t=await tx.tournament.findUnique({where:{id},include:{_count:{select:{matches:true}}}});if(!t)throw new AppError(404,'Tournament not found.');if(!transitions[t.status].includes(status))throw new AppError(409,`Cannot move ${t.status} to ${status}.`);if(status==='REGISTRATION_OPEN'&&(t.registrationDeadline<=new Date()||t._count.matches))throw new AppError(409,'Registration cannot reopen after its deadline or after fixtures exist.');if(status==='ONGOING'&&!t._count.matches)throw new AppError(409,'Generate fixtures before starting play.');const result=await tx.tournament.update({where:{id},data:{status,publishedAt:t.publishedAt??new Date(),version:{increment:1}}});if(status==='CANCELLED')await tx.match.updateMany({where:{tournamentId:id,status:{notIn:['COMPLETED','WALKOVER']}},data:{status:'CANCELLED'}});await audit(tx,actorId,'STATUS_'+status,id,{reason});return result})}
export async function remove(actorId:string,id:string,reason:string,confirmation:string){return transaction(async tx=>{
 const actor=await tx.user.findUnique({where:{id:actorId}});if(!actor||!['ADMIN','SUPER_ADMIN'].includes(actor.role)||actor.status!=='ACTIVE'||actor.deletedAt)throw new AppError(403,'Only administrators can delete tournaments.');
 const t=await tx.tournament.findUnique({where:{id},include:{participants:{select:{userId:true}}}});if(!t)throw new AppError(404,'Tournament not found.');if(confirmation!==t.slug)throw new AppError(422,'Enter the exact tournament slug to confirm deletion.');
 const champions=await tx.tournamentWinner.findMany({where:{tournamentId:id,place:1},select:{participant:{select:{userId:true}}}});
 await tx.tournamentWinner.deleteMany({where:{tournamentId:id}});
 await tx.standing.deleteMany({where:{tournamentId:id}});
 await tx.match.deleteMany({where:{tournamentId:id}});
 await tx.tournamentGroup.deleteMany({where:{tournamentId:id}});
 await tx.tournament.delete({where:{id}});
 for(const winner of champions){if(!await tx.tournamentWinner.count({where:{place:1,participant:{userId:winner.participant.userId}}}))await tx.userAchievement.deleteMany({where:{userId:winner.participant.userId,achievement:{code:'TOURNAMENT_CHAMPION'}}});}
 await tx.notification.createMany({data:t.participants.map(p=>({userId:p.userId,title:'Tournament deleted',message:t.name+' was deleted by an administrator. '+reason,type:'TOURNAMENT_DELETED',link:'/dashboard/tournaments'}))});
 await audit(tx,actorId,'TOURNAMENT_DELETED',id,{reason,name:t.name,status:t.status});return null;
})}
export async function join(userId:string,id:string){return transaction(async tx=>{const [user,t,existing]=await Promise.all([tx.user.findUnique({where:{id:userId},include:{profile:true}}),tx.tournament.findUnique({where:{id}}),tx.tournamentRegistration.findUnique({where:{tournamentId_userId:{tournamentId:id,userId}}})]);if(!user||user.status!=='ACTIVE')throw new AppError(403,'Your account is not eligible to register.');if(!user.emailVerified)throw new AppError(403,'Verify your email before joining.');if(!t||t.visibility==='PRIVATE'||!t.publishedAt)throw new AppError(404,'Tournament not found.');const now=new Date();if(t.status!=='REGISTRATION_OPEN'||t.registrationStartsAt>now||t.registrationDeadline<=now)throw new AppError(409,'Tournament registration is closed.');if(user.profile?.platform!==t.platform)throw new AppError(409,'Your platform does not match this tournament.');if(existing&&existing.status!=='WITHDRAWN')throw new AppError(409,'You already have a registration for this tournament.');const count=await tx.tournamentRegistration.count({where:{tournamentId:id,status:{in:['PENDING','APPROVED']}}});if(count>=t.maxPlayers)throw new AppError(409,'This tournament is full.');const status=t.manualApproval?'PENDING':'APPROVED';const registration=await tx.tournamentRegistration.upsert({where:{tournamentId_userId:{tournamentId:id,userId}},create:{tournamentId:id,userId,status,rulesAcceptedAt:now},update:{status,rulesAcceptedAt:now,reviewReason:null,reviewedAt:null}});if(status==='APPROVED')await tx.tournamentParticipant.create({data:{tournamentId:id,userId}});await tx.notification.create({data:{userId,title:status==='APPROVED'?'Registration approved':'Registration submitted',message:t.name,type:'REGISTRATION',link:'/tournaments/'+t.slug}});return registration})}
export async function withdraw(userId:string,id:string){return transaction(async tx=>{const t=await tx.tournament.findUnique({where:{id},include:{_count:{select:{matches:true}}}});if(!t||!t.withdrawalAllowed||t.registrationDeadline<=new Date()||t._count.matches)throw new AppError(409,'Withdrawal is no longer available. Contact an administrator.');const reg=await tx.tournamentRegistration.updateMany({where:{tournamentId:id,userId,status:{in:['PENDING','APPROVED']}},data:{status:'WITHDRAWN'}});if(reg.count!==1)throw new AppError(409,'No active registration to withdraw.');await tx.tournamentParticipant.deleteMany({where:{tournamentId:id,userId}});return null})}
export async function reviewRegistration(actorId:string,id:string,approve:boolean,reason:string){return transaction(async tx=>{const r=await tx.tournamentRegistration.findUnique({where:{id},include:{tournament:{include:{_count:{select:{matches:true}}}},user:true}});if(!r)throw new AppError(404,'Registration not found.');if(r.status!=='PENDING'||r.tournament._count.matches||['CANCELLED','COMPLETED'].includes(r.tournament.status))throw new AppError(409,'This registration cannot be reviewed now.');if(approve&&r.user.status!=='ACTIVE')throw new AppError(409,'The player is restricted.');if(approve){const count=await tx.tournamentParticipant.count({where:{tournamentId:r.tournamentId}});if(count>=r.tournament.maxPlayers)throw new AppError(409,'The tournament is full.');await tx.tournamentParticipant.create({data:{tournamentId:r.tournamentId,userId:r.userId}})}const result=await tx.tournamentRegistration.update({where:{id},data:{status:approve?'APPROVED':'REJECTED',reviewReason:reason,reviewedAt:new Date()}});await audit(tx,actorId,approve?'REGISTRATION_APPROVED':'REGISTRATION_REJECTED',r.tournamentId,{registrationId:id,reason});await tx.notification.create({data:{userId:r.userId,title:approve?'Registration approved':'Registration declined',message:r.tournament.name+'. '+reason,type:'REGISTRATION',link:'/tournaments/'+r.tournament.slug}});return result})}
export function adminList(){return prisma.tournament.findMany({take:100,orderBy:{createdAt:'desc'},include:{_count:{select:{participants:true,matches:true}},createdBy:{select:{name:true}}}})}

