import {passwordStrength} from './password.js';
export {passwordStrength, type PasswordStrength} from './password.js';
import { z } from 'zod';
export const platformSchema = z.enum(['PLAYSTATION','XBOX','STEAM_PC','MOBILE']);
export const supportedPlatformSchema=z.enum(['STEAM_PC','MOBILE']);
export const roleSchema = z.enum(['PLAYER','ADMIN','SUPER_ADMIN']);
export const passwordSchema = z.string().min(8,'Use at least 8 characters').max(72,'Use at most 72 characters').refine(value => new TextEncoder().encode(value).length <= 72, 'Password must be at most 72 UTF-8 bytes').refine(value => passwordStrength(value) !== 'Poor', 'Choose a medium or strong password. Use 8+ characters with three character types, or 16+ with two; avoid common passwords.');
const username = z.string().trim().min(3).max(24).regex(/^[a-zA-Z0-9_]+$/,'Use letters, numbers and underscores').transform(v=>v.toLowerCase());
export const registerSchema = z.object({name:z.string().trim().min(2).max(80),username,email:z.email().trim().toLowerCase().max(254),password:passwordSchema,confirmPassword:z.string(),country:z.string().trim().length(2,'Use a two-letter country code').toUpperCase(),efootballUsername:z.string().trim().min(2).max(40),platform:supportedPlatformSchema}).strict().refine(v=>v.password===v.confirmPassword,{path:['confirmPassword'],message:'Passwords must match'});
export const loginSchema=z.object({email:z.string().trim().min(2,'Enter your email, username or eFootball username.').max(254).transform(v=>v.toLowerCase()),password:z.string().min(1).max(200)}).strict();
export const emailSchema=z.object({email:z.email().trim().toLowerCase()}).strict();
export const tokenSchema=z.object({token:z.string().regex(/^[a-f0-9]{64}$/,'Invalid or expired link')}).strict();
export const resetPasswordSchema=tokenSchema.extend({password:passwordSchema,confirmPassword:z.string()}).refine(v=>v.password===v.confirmPassword,{path:['confirmPassword'],message:'Passwords must match'});
export const profileSchema=z.object({name:z.string().trim().min(2).max(80),country:z.string().length(2).toUpperCase(),platform:supportedPlatformSchema,efootballUsername:z.string().trim().min(2).max(40),efootballUserId:z.string().trim().max(40).optional(),platformUsername:z.string().trim().max(60).optional(),timezone:z.string().refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true}catch{return false}},'Choose a valid timezone'),publicHistory:z.boolean()}).strict();
export type RegisterInput=z.infer<typeof registerSchema>;
export type LoginInput=z.infer<typeof loginSchema>;
export type ProfileInput=z.infer<typeof profileSchema>;
export type Role=z.infer<typeof roleSchema>;
export interface SessionUser {id:string;name:string;username:string;email:string;role:Role;emailVerified:boolean;status:'ACTIVE'|'SUSPENDED'|'BANNED';createdAt:string;profile:{country:string;platform:z.infer<typeof platformSchema>;efootballUsername:string;efootballUserId:string|null;platformUsername:string|null;timezone:string;avatarUrl:string|null;publicHistory:boolean}|null}
export interface ApiResponse<T>{success:true;message:string;data:T}
export interface ApiFailure{success:false;message:string;errors:Array<{path:string;message:string}>;requestId?:string}
export const tournamentSchema=z.object({name:z.string().trim().min(3).max(120),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(140),description:z.string().trim().min(10).max(5000),format:z.enum(['LEAGUE','GROUP_STAGE','KNOCKOUT','GROUP_KNOCKOUT']),platform:supportedPlatformSchema,region:z.string().min(2).max(60),minPlayers:z.number().int().min(2).max(128),maxPlayers:z.number().int().min(2).max(128),registrationStartsAt:z.iso.datetime(),registrationDeadline:z.iso.datetime(),startsAt:z.iso.datetime(),endsAt:z.iso.datetime().nullable().optional(),matchDuration:z.number().int().min(5).max(30),rules:z.string().min(20).max(10000),prizeInfo:z.string().max(1000).optional(),entryFee:z.number().min(0).max(100000).default(0),numberOfGroups:z.number().int().min(0).max(32).default(0),advancingPerGroup:z.number().int().min(1).max(16).default(2),homeAwayLegs:z.boolean().default(false),thirdPlaceEnabled:z.boolean().default(false),pointsWin:z.number().int().min(0).max(10).default(3),pointsDraw:z.number().int().min(0).max(10).default(1),pointsLoss:z.number().int().min(0).max(10).default(0),goalDifferenceTiebreak:z.boolean().default(true),headToHeadTiebreak:z.boolean().default(true),manualQualification:z.boolean().default(true),manualApproval:z.boolean().default(false),withdrawalAllowed:z.boolean().default(true),participantListPublic:z.boolean().default(true),visibility:z.enum(['PUBLIC','UNLISTED','PRIVATE']).default('PUBLIC')}).strict().superRefine((v,ctx)=>{if(v.minPlayers>v.maxPlayers)ctx.addIssue({code:'custom',path:['maxPlayers'],message:'Capacity must be at least the minimum player count.'});if(v.registrationStartsAt>=v.registrationDeadline||v.registrationDeadline>=v.startsAt)ctx.addIssue({code:'custom',path:['startsAt'],message:'Registration must open, close, then kickoff in that order.'});if(v.endsAt&&v.endsAt<=v.startsAt)ctx.addIssue({code:'custom',path:['endsAt'],message:'End date must follow kickoff.'});if(v.format.includes('GROUP')&&(v.numberOfGroups<2||v.maxPlayers<v.numberOfGroups*2||v.advancingPerGroup>Math.floor(v.maxPlayers/v.numberOfGroups)))ctx.addIssue({code:'custom',path:['numberOfGroups'],message:'Choose valid groups and advancing players for this capacity.'})});
export type TournamentInput=z.infer<typeof tournamentSchema>;
export const scoreSchema=z.object({homeScore:z.number().int().min(0).max(99),awayScore:z.number().int().min(0).max(99),homePenalties:z.number().int().min(0).max(99).nullable().optional(),awayPenalties:z.number().int().min(0).max(99).nullable().optional(),evidenceId:z.uuid().optional()}).strict();
export type ScoreInput=z.infer<typeof scoreSchema>;
