'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Bell} from 'lucide-react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from '@/lib/api';
import {notificationTone} from '@/lib/notification-sound';
import type {Notice} from '@/lib/competition';
export function NotificationBell({userId}:{userId:string}){
 const cache=useQueryClient(),[open,setOpen]=useState(false),[toast,setToast]=useState<Notice|null>(null),[soundEnabled,setSoundEnabled]=useState(false),[soundMessage,setSoundMessage]=useState(''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('');
 const previous=useRef<string|null|undefined>(undefined);
 useEffect(()=>{try{setSoundEnabled(localStorage.getItem('touchline.sound.'+userId)==='on')}catch{/* Storage is optional. */}},[userId]);
 const {data,error}=useQuery({queryKey:['notifications',userId],queryFn:()=>api<Notice[]>('/notifications'),refetchInterval:3000,refetchIntervalInBackground:true});
 useEffect(()=>{if(!data)return;const latest=data[0];if(previous.current!==undefined&&latest&&latest.id!==previous.current&&!latest.readAt){setToast(latest);if(soundEnabled)void notificationTone()}previous.current=latest?.id||null},[data,soundEnabled]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(null),6000);return()=>clearTimeout(timer)},[toast]);
 const count=data?.filter(n=>!n.readAt).length||0;
 async function refresh(){await cache.invalidateQueries({queryKey:['notifications',userId]});await cache.invalidateQueries({queryKey:['dashboard']})}
 async function read(id:string){try{await api('/notifications/'+id+'/read',{method:'PATCH'});await refresh()}catch{setFeedback('Could not mark the notification as read.')}}
 async function readAll(){setBusy(true);setFeedback('');try{await api('/notifications/read-all',{method:'PATCH'});setToast(null);await refresh();setFeedback('All notifications marked as read.')}catch{setFeedback('Unable to mark notifications as read. Please try again.')}finally{setBusy(false)}}
 return <div className="notification-bell"><button className="button button-ghost" aria-label={`Notifications${count?`, ${count} unread`:''}`} aria-expanded={open} aria-controls="notification-menu" onClick={()=>{setOpen(!open);setToast(null)}}><Bell size={20}/>{count>0&&<span className="notification-count">{count>99?'99+':count}</span>}</button>{open&&<section id="notification-menu" className="notification-menu" aria-label="Recent notifications"><div className="row"><h2>Notifications</h2><button className="button button-ghost" aria-label="Close notifications" onClick={()=>setOpen(false)}>×</button></div><button className="button button-outline notification-sound" disabled={busy||!count} onClick={()=>void readAll()}>{busy?'Marking as read…':'Mark all as read'}</button><p className="small muted" role="status">{feedback}</p><button className="button button-outline notification-sound" aria-pressed={soundEnabled} onClick={async()=>{const enabled=!soundEnabled;if(enabled&&!await notificationTone()){setSoundMessage('Audio could not start. Try again after checking browser sound settings.');return}setSoundEnabled(enabled);setSoundMessage(enabled?'Notification sound enabled.':'Notifications muted.');try{localStorage.setItem('touchline.sound.'+userId,enabled?'on':'off')}catch{/* Storage is optional. */}}}>{soundEnabled?'Mute notification sound':'Enable notification sound'}</button><p className="small muted" role="status">{soundMessage||'Enable once to hear a chime for new messages.'}</p>{error?<p role="alert">Could not load notifications. Try again shortly.</p>:data?.length?data.slice(0,6).map(n=><Link key={n.id} className={'notification-item'+(!n.readAt?' unread':'')} href={n.link||'/dashboard/notifications'} onClick={()=>{setOpen(false);void read(n.id)}}><strong>{n.title}</strong><span>{n.message}</span></Link>):<p className="muted">No notifications yet.</p>}<Link className="lime small" href="/dashboard/notifications" onClick={()=>setOpen(false)}>View all notifications →</Link></section>}{toast&&!open&&<div className="notification-toast" role="status"><Link href={toast.link||'/dashboard/notifications'} onClick={()=>{setToast(null);void read(toast.id)}}><strong>{toast.title}</strong><span>{toast.message}</span></Link><button aria-label="Dismiss notification" onClick={()=>setToast(null)}>×</button></div>}</div>;
}
