import fs from 'node:fs';
let f='apps/api/src/services/fixture.service.ts',s=fs.readFileSync(f,'utf8');s="import {rankScope} from './ranking.service.js';\n"+s.replace('roundRobin,distributeGroups,calculateStandings','roundRobin,distributeGroups');let start=s.indexOf('export async function qualify('),end=s.indexOf('export async function confirmQualification(',start);s=s.slice(0,start)+`export async function qualify(tx:Prisma.TransactionClient,t:Tournament){
 const remaining=await tx.match.count({where:{tournamentId:t.id,stage:'GROUP',status:{notIn:['COMPLETED','WALKOVER']}}});if(remaining)throw new AppError(409,'All group matches must have official results before qualification.');
 if(await tx.match.count({where:{tournamentId:t.id,stage:{in:['KNOCKOUT','FINAL']}}}))throw new AppError(409,'Knockout stage already exists.');
 const groups=await tx.tournamentGroup.findMany({where:{tournamentId:t.id},orderBy:{position:'asc'}});if(!groups.length)throw new AppError(409,'No groups exist.');
 const qualified:TournamentParticipant[]=[];for(const group of groups){const ranking=await rankScope(tx,t,group.id);if(ranking.tiedAt(t.advancingPerGroup))return {qualified:0,requiresReview:true};const top=ranking.rows.slice(0,t.advancingPerGroup);if(top.length<t.advancingPerGroup)throw new AppError(409,'A group has insufficient qualifiers.');for(const row of top)qualified.push(ranking.members.find(m=>m.id===row.participantId)!)}
 for(const p of qualified)await tx.tournamentParticipant.update({where:{id:p.id},data:{qualified:true}});await tx.tournamentGroup.updateMany({where:{tournamentId:t.id},data:{qualificationConfirmedAt:new Date()}});await createKnockout(tx,t,qualified);await tx.tournament.update({where:{id:t.id},data:{currentStage:'KNOCKOUT'}});await tx.notification.createMany({data:qualified.map(p=>({userId:p.userId,title:'You qualified for the knockout stage',message:t.name,type:'QUALIFICATION',link:'/tournaments/'+t.slug}))});return {qualified:qualified.length,requiresReview:false};
}
`+s.slice(end);s=s.replace("const result=await qualify(tx,t);await audit", "const result=await qualify(tx,t);if(result.requiresReview)throw new AppError(409,'A qualification place is tied. Record a manual tie-break ranking first.');await audit");fs.writeFileSync(f,s);
f='apps/api/src/services/result.service.ts';s=fs.readFileSync(f,'utf8');s=s.replace(/import \{qualify\} from '.\/fixture.service.js';/,'').replace(/import \{ qualify \} from "\.\/fixture.service.js";/,'');s="import {finishCompetition} from './lifecycle.service.js';\n"+s;start=s.indexOf('  if (!outstanding) {');end=s.indexOf('  await tx.notification.createMany({',start);if(start<0||end<0)throw Error('Result lifecycle marker missing');s=s.slice(0,start)+'  if (!outstanding) await finishCompetition(tx,m.tournament,m.stage);\n'+s.slice(end);fs.writeFileSync(f,s);
