import 'dotenv/config';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import bcrypt from 'bcrypt';
import {prisma} from '../src/config/prisma.js';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/Golam Rabbi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ids:string[]=[];let tid='';const browser=await chromium.launch({headless:true,channel:'msedge'});
try{const password='Browser-'+randomUUID()+'!';const hash=await bcrypt.hash(password,12);const users=[];
for(let i=0;i<3;i++){const key=randomUUID().slice(0,8);const u=await prisma.user.create({data:{name:'Room Player '+i,username:'room_'+key,email:'room_'+key+'@example.com',passwordHash:hash,emailVerified:true,role:i===2?'ADMIN':'PLAYER',profile:{create:{platform:'STEAM_PC',country:'BD',efootballUsername:'Room_'+key}}}});ids.push(u.id);users.push(u);}
const t=await prisma.tournament.create({data:{name:'Room browser fixture',slug:'room-'+randomUUID(),description:'Isolated browser verification',format:'KNOCKOUT',platform:'STEAM_PC',maxPlayers:4,registrationStartsAt:new Date(Date.now()-86400000),registrationDeadline:new Date(Date.now()-7200000),startsAt:new Date(Date.now()-3600000),rules:'Coordinate and report official results.',createdById:ids[2]!,status:'ONGOING',publishedAt:new Date()}});tid=t.id;
const players=await Promise.all(ids.slice(0,2).map(userId=>prisma.tournamentParticipant.create({data:{tournamentId:tid,userId}})));
const m=await prisma.match.create({data:{tournamentId:tid,stage:'FINAL',round:1,position:1,homeId:players[0]!.id,awayId:players[1]!.id,scheduledAt:new Date(Date.now()-20*60000)}});
const pages=[];for(const u of users){const context=await browser.newContext({viewport:{width:390,height:844}});const p=await context.newPage();const response=await context.request.post('http://localhost:4100/api/v1/auth/login',{headers:{Origin:'http://localhost:3100'},data:{email:u.email,password}});if(response.status()!==200)throw Error('Fixture login failed');await p.goto('http://localhost:3100/matches/'+m.id);await p.getByRole('heading',{name:'Private match coordination'}).waitFor();pages.push(p);}
await pages[0].getByRole('button',{name:'Check in · I’m ready'}).click();await pages[0].getByText('✓ Ready to play',{exact:true}).waitFor();
await pages[0].getByRole('button',{name:'Edit lobby details'}).click();await pages[0].getByLabel('Game room ID and coordination instructions').fill('Room 12345 — ready for kickoff');await pages[0].getByRole('button',{name:'Save lobby details'}).click();await pages[1].getByText('Room 12345 — ready for kickoff',{exact:true}).waitFor();
await pages[0].getByText('Report opponent no-show',{exact:true}).click();await pages[0].getByLabel('Describe your attempts to contact the opponent').fill('No reply after waiting twenty minutes in the lobby.');pages[0].once('dialog',(d:{accept:()=>Promise<void>})=>d.accept());await pages[0].getByRole('button',{name:'Submit no-show report'}).click();await pages[2].getByText('Review no-show report',{exact:true}).waitFor();await pages[2].getByText('Review no-show report',{exact:true}).click();await pages[2].getByLabel('Decision and next steps').fill('Both players should agree a new time before playing.');pages[2].once('dialog',(d:{accept:()=>Promise<void>})=>d.accept());await pages[2].getByRole('button',{name:'Publish decision'}).click();await pages[1].getByText('Report reviewed',{exact:true}).waitFor();
for(const p of pages){if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');}
await pages[0].goto('http://localhost:3100/dashboard/settings');const saved=pages[0].waitForResponse((r:{url:()=>string;request:()=>{method:()=>string}})=>r.url().includes('notification-preferences')&&r.request().method()==='PATCH');await pages[0].getByLabel('Remind me when match check-in opens').uncheck();await saved;await pages[0].reload();if(await pages[0].getByLabel('Remind me when match check-in opens').isChecked())throw Error('Preference failed to persist');console.log('PASS: two-player readiness/lobby, no-show report, administrator decision, mobile width, reminder preference persistence');
}finally{await browser.close();if(tid)await prisma.tournament.delete({where:{id:tid}});await prisma.auditLog.deleteMany({where:{actorId:{in:ids}}});await prisma.user.deleteMany({where:{id:{in:ids}}});await prisma.$disconnect();}


